### ISSUE TITLE
Doesn't compile for Ubuntu 18.04

### ISSUE THREAD

**Issue by AlbyIanna** [destegabry/ricettario#3]
I'm trying to cook a [Maialetto Sardo](https://github.com/destegabry/ricettario/blob/master/carne/maialetto-sardo.md) but I can't compile it on my machine (I'm running Ubuntu 18.04)

I somehow managed to download and install all the ingredients (it was especially difficult to find the **Rametti di mirto**, apparently there is only a single repository that doesn't respond with a 404 when you try to install it and it's located at [Quartu Sant'Elena](https://en.wikipedia.org/wiki/Quartu_Sant%27Elena)). 

I'm following the [steps to prepare it](https://github.com/destegabry/ricettario/blob/master/carne/maialetto-sardo.md#preparazione), I covered my porceddu with salt, then massaged it carefully. Then I followed instructions at step 2, although I didn't figure out what a `cotenna` is... It would be great if you could translate this tutorial in English, Spanish and Swedish! :wink:
Now I'm getting a compilation error when running instructions at step 3. You can see the output in the image below :point_down: 
![image](https://user-images.githubusercontent.com/6939054/76576004-1f9bee80-64c1-11ea-945b-c172503347db.png)

Here's more detailed info about my machine:
```
System:    Host: alberto-Lenovo-Y50-70 Kernel: 5.3.0-40-generic x86_64 bits: 64 Desktop: Gnome 3.28.4
           Distro: Ubuntu 18.04.3 LTS
Machine:   Device: laptop System: LENOVO product: 20378 v: Lenovo Y50-70 serial: N/A
           Mobo: LENOVO model: Lenovo Y50-70 v: 31900058WIN serial: N/A
           UEFI [Legacy]: LENOVO v: 9ECN43WW(V3.03) date: 08/12/2015
Battery    BAT1: charge: 40.5 Wh 99.9% condition: 40.5/54.8 Wh (74%)
CPU:       Quad core Intel Core i7-4710HQ (-MT-MCP-) cache: 6144 KB
           clock speeds: max: 3500 MHz 1: 1475 MHz 2: 2041 MHz 3: 2016 MHz 4: 1577 MHz 5: 1205 MHz 6: 1405 MHz
           7: 1789 MHz 8: 1626 MHz
Graphics:  Card-1: Intel 4th Gen Core Processor Integrated Graphics Controller
           Card-2: NVIDIA GM107M [GeForce GTX 860M]
           Display Server: x11 (X.Org 1.20.5 ) drivers: i915,nouveau
           Resolution: 1920x1080@60.05hz, 1920x1080@60.00hz
           OpenGL: renderer: Mesa DRI Intel Haswell Mobile version: 4.5 Mesa 19.2.8
Audio:     Card-1 Intel 8 Series/C220 Series High Definition Audio Controller driver: snd_hda_intel
           Card-2 Intel Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller driver: snd_hda_intel
           Sound: Advanced Linux Sound Architecture v: k5.3.0-40-generic
Network:   Card-1: Intel Wireless 3160 driver: iwlwifi
           IF: wlp8s0 state: up mac: d0:7e:35:30:c5:46
           Card-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller driver: r8169
           IF: enp9s0 state: down mac: f0:76:1c:1f:45:7f
Drives:    HDD Total Size: 1000.2GB (7.6% used)
           ID-1: /dev/sda model: Samsung_SSD_860 size: 1000.2GB
Partition: ID-1: / size: 98G used: 71G (76%) fs: ext4 dev: /dev/sda5
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 52.0C mobo: N/A gpu: 43.0
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 373 Uptime: 15 min Memory: 3422.5/7877.8MB Client: Shell (bash) inxi: 2.3.56 
```

Anyone else's having similar issues?

P.S.: @smellai @destegabry isolation is booooring :smile:

**Comment by destegabry** [comment]
This issue happens randomly and we're still trying to figure out why.

I suggest you to try some other recipes like [this one](https://github.com/destegabry/ricettario/blob/master/pesce/oktapodi-krasato.md), which doesn't involve using that kind of hardware.

**Comment by ghost** [comment]
Somebody says that this may happen when continentals try to compile a proceddu...
